export const ACTION_INTERACTION_INITIATED = 'INIT_INTERACTION';
export const INTERACTION_RESPONDED = 'INTERACTION_RESPOND';
export const INTERACTION_COMPLETE = 'INTERACTION_COMPLETE';

export const STATUS_NO_VIEW = 'NOT_YET_VIEWED';
export const STATUS_NO_RESPOND = 'NOT_YET_VIEWED';
export const STATUS_PARTIAL_RESPONSE = 'RESPONSE_STARTED';
export const STATUS_COMPLETE = 'RESPONSE_SENT';